[tool.poetry]
name = "aoc2023py"
version = "0.1.0"
description = ""
authors = ["kle <kle@axon.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
networkx = "^3.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
